const annotations = [
  [
    {
      note: { label: "1. East Asian Language" },
      x: 190,
      y: 100,
      dy: -17,
      dx: 92,
      subject: { radius: 100, radiusPadding: 10 },
    },
    {
      note: { label: "European & Middle Eastern" },
      x: 600,
      y: 450,
      dy: -17,
      dx: 92,
      subject: { radius: 100, radiusPadding: 10 },
    },
    {
      note: { label: "2. South Asian, African, and Other" },
      x: 1200,
      y: 500,
      dy: -17,
      dx: 92,
      subject: { radius: 100, radiusPadding: 10 },
    },
  ],
  [
    {
      note: { label: "2. A Mix of East Asian & European" },
      x: 200,
      y: 250,
      dy: -17,
      dx: 92,
      subject: { radius: 100, radiusPadding: 10 },
    },
    {
      note: { label: "Introduction of Slavic Language" },
      x: 550,
      y: 300,
      dy: -17,
      dx: 92,
      subject: { radius: 100, radiusPadding: 10 },
    },
    {
      note: { label: "Predominantly South Asian Languages" },
      x: 1200,
      y: 500,
      dy: -17,
      dx: 92,
      subject: { radius: 100, radiusPadding: 10 },
    },
  ],
  [
    {
      note: { label: "3. The Ascent of the Eastern Languages" },
      x: 250,
      y: 250,
      dy: -17,
      dx: 92,
      subject: { radius: 100, radiusPadding: 10 },
    },
    {
      note: { label: "The Stable Growth of European Languages" },
      x: 550,
      y: 300,
      dy: -17,
      dx: 92,
      subject: { radius: 100, radiusPadding: 10 },
    },
    {
      note: { label: "The Stable Growth of Others" },
      x: 1200,
      y: 500,
      dy: -17,
      dx: 92,
      subject: { radius: 100, radiusPadding: 10 },
    },
  ],
  [
    {
      note: { label: "4. Massive Spike in Chinese" },
      x: 190,
      y: 100,
      dy: -17,
      dx: 92,
      subject: { radius: 100, radiusPadding: 10 },
    },
    {
      note: { label: "Potential Change of Rank" },
      x: 300,
      y: 250,
      dy: -17,
      dx: 92,
      subject: { radius: 100, radiusPadding: 10 },
    },
    {
      note: { label: "Stagnation on the Lower Bound" },
      x: 1200,
      y: 500,
      dy: -17,
      dx: 92,
      subject: { radius: 100, radiusPadding: 10 },
    },
  ],
  [
    {
      note: { label: "5. The Eastern Shift" },
      x: 200,
      y: 250,
      dy: -17,
      dx: 92,
      subject: { radius: 100, radiusPadding: 10 },
    },
    {
      note: { label: "Moderate Growth of European Languages" },
      x: 550,
      y: 300,
      dy: -17,
      dx: 92,
      subject: { radius: 100, radiusPadding: 10 },
    },
    {
      note: { label: "Moderate Growth of Other Languages" },
      x: 1200,
      y: 500,
      dy: -17,
      dx: 92,
      subject: { radius: 100, radiusPadding: 10 },
    },
  ],
  [
    {
      note: { label: "6. Chinese Lift Off" },
      x: 200,
      y: 250,
      dy: -17,
      dx: 92,
      subject: { radius: 100, radiusPadding: 10 },
    },
    {
      note: { label: "Vietnamese Eclipses French" },
      x: 550,
      y: 300,
      dy: -17,
      dx: 92,
      subject: { radius: 100, radiusPadding: 10 },
    },
    {
      note: { label: "A Predictable Long Tail" },
      x: 1200,
      y: 500,
      dy: -17,
      dx: 92,
      subject: { radius: 100, radiusPadding: 10 },
    },
  ],
  [
    {
      note: { label: "7. Chinese is (Literally) off the Charts!" },
      x: 200,
      y: 250,
      dy: -17,
      dx: 92,
      subject: { radius: 100, radiusPadding: 10 },
    },
    {
      note: { label: "Korean Gaining on French and Possible Arabic Overtaking" },
      x: 550,
      y: 300,
      dy: -17,
      dx: 92,
      subject: { radius: 100, radiusPadding: 10 },
    },
    {
      note: { label: "Predictable Rises" },
      x: 1200,
      y: 500,
      dy: -17,
      dx: 92,
      subject: { radius: 100, radiusPadding: 10 },
    },
  ],
  [
    {
      note: { label: "8. PAGE TWO" },
      x: 200,
      y: 250,
      dy: -17,
      dx: 92,
      subject: { radius: 100, radiusPadding: 10 },
    },
    {
      note: { label: "Languages other than English & Spanish" },
      x: 550,
      y: 300,
      dy: -17,
      dx: 92,
      subject: { radius: 100, radiusPadding: 10 },
    },
    {
      note: { label: "Languages other than English & Spanish" },
      x: 1200,
      y: 500,
      dy: -17,
      dx: 92,
      subject: { radius: 100, radiusPadding: 10 },
    },
  ],
]


export default annotations